name: Black Code Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    name: Format with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          token: ${{secrets.PAT}}

      - name: Check Commit Author's Email
        id: check_commit_author
        run: |
          COMMITTER_EMAIL=$(git log -1 --format='%ae')
          echo "Committer's email: $COMMITTER_EMAIL"
          if [ "$COMMITTER_EMAIL" = "action@github.com" ]; then
            echo "Skipping workflow for specific email address."
            exit 0
          fi 

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Format code with Black
        run: black . --line-length=250

      - name: Commit changes
        if: github.actor != "actions-user"
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto-format code using black"
          git push   
          
